# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tape.tv engineering
email: tech@tape.tv
description: > A technical blog run by the engineers at tape.tv
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tape-tv.github.io" # the base hostname & protocol for your site
twitter_username: tape_tv
github_username:  tape-tv

# Build settings
markdown: kramdown
